### ISSUE TITLE
Can't request location updates via pending intent from non-ui thread

### ISSUE THREAD

**Issue by amayatsky** [mapzen/lost#131]
### Description

Request location updates via pending intent from a service, from non-ui thread fails.
### Steps to Reproduce

Simply request location updates from a non-main thread.
### Lost & Android Version

2.1.1, Android 7.0 (24)
### Log

java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                         at android.os.Handler.<init>(Handler.java:200)
                                                                                         at android.os.Handler.<init>(Handler.java:114)
                                                                                         at android.location.LocationManager$ListenerTransport$1.<init>(LocationManager.java:239)
                                                                                         at android.location.LocationManager$ListenerTransport.<init>(LocationManager.java:239)
                                                                                         at android.location.LocationManager.wrapListener(LocationManager.java:871)
                                                                                         at android.location.LocationManager.requestLocationUpdates(LocationManager.java:884)
                                                                                         at android.location.LocationManager.requestLocationUpdates(LocationManager.java:471)
                                                                                         at com.mapzen.android.lost.internal.FusionEngine.enableNetwork(FusionEngine.java:133)
                                                                                         at com.mapzen.android.lost.internal.FusionEngine.enable(FusionEngine.java:107)
                                                                                         at com.mapzen.android.lost.internal.LocationEngine.setRequest(LocationEngine.java:45)
                                                                                         at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.requestLocationUpdates(FusedLocationProviderServiceImpl.java:65)
                                                                                         at com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(FusedLocationProviderService.java:74)
                                                                                         at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:127)
                                                                                         at *.BackgroundLocationService.requestUpdates(BackgroundLocationService.java:168)

**Comment by ecgreb** [comment]
Interesting this is exception occurs pretty deep inside the `LocationManager`.

Do we know if this use case is supported when calling [`LocationManager.requestLocationUpdates(long minTime, float minDistance, Criteria criteria, PendingIntent intent)`](https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(long, float, android.location.Criteria, android.app.PendingIntent)) directly from a non-UI thread in an application?

**Comment by ecgreb** [comment]
It seems this is the expected behavior and is even [documented as such in Google Play services](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi.html#requestLocationUpdates(com.google.android.gms.common.api.GoogleApiClient,%20com.google.android.gms.location.LocationRequest,%20com.google.android.gms.location.LocationListener)
).

Closing this issue now but feel free to re-open if you find any deviations between Lost and the Google Play services version.

**Comment by amayatsky** [comment]
@ecgreb I think you are looking at the wrong method.
I am talking about [background updates via Pending Intent](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi.html#requestLocationUpdates(com.google.android.gms.common.api.GoogleApiClient, com.google.android.gms.location.LocationRequest, android.app.PendingIntent).
As far as you can see there is no requirement to make this call from a main thread.

**Comment by ecgreb** [comment]
Ah yes so I was looking at the wrong method sorry about that. I will take another look at the issue requesting updates from a non-UI thread with a `PendingIntent`.

**Comment by sarahlensing** [comment]
@amayatsky this has been resolved in the `2.3.0-SNAPSHOT`. Please upgrade to that version or wait for an official release. Thank you!
