### ISSUE TITLE
Crash on screen rotate with multiple lostApiClients

### ISSUE THREAD

**Issue by westnordost** [mapzen/lost#170]
### Description
When I rotate the screen in my [app](https://github.com/westnordost/streetcomplete), LOST throws the following exception:
```
java.lang.IllegalArgumentException: Client must be added before requesting location updates
    at com.mapzen.android.lost.internal.LostClientManager.throwIfClientNotAdded(LostClientManager.java:98)
    at com.mapzen.android.lost.internal.LostClientManager.addListener(LostClientManager.java:76)
    at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.requestLocationUpdates(FusedLocationProviderServiceImpl.java:59)
    at com.mapzen.android.lost.internal.FusedLocationProviderService.requestLocationUpdates(FusedLocationProviderService.java:69)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:109)
    at de.westnordost.streetcomplete.tangram.MapFragment.onConnected(MapFragment.java:448)
    at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1214)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1231)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```
### Steps to Reproduce
It is always reproducable within my app but unknown for a minimal sample project.
The usage of LOST in my app is a little more complex, since I use several LostApiClients from within different classes. Basically, each fragment that uses a LostApiClient makes the following calls in this order:

1. in `onAttach`, a LostApiClient is built using `new LostApiClient.Builder(context).addConnectionCallbacks(this).build()`
2. some time later (when another fragment ensured the user has all permissions and GPS is on), `startPositionTracking()` in the fragment is called, which executes `if(!lostApiClient.isConnected()) lostApiClient.connect();`
3. in `onConnected`, finally `LocationServices.FusedLocationApi.requestLocationUpdates(lostApiClient, request, this)` is called.
4. later in `onStop` or from outside, `stopPositionTracking()` is called in the fragment, which executes the following code: `LocationServices.FusedLocationApi.removeLocationUpdates(lostApiClient, this); lostApiClient.disconnect();`
5. when rotating the screen, 1. and 2. is called thereafter, LOST throws the exception in 3.

### Lost & Android Version
LOST 2.2.0, Android 5.1.1

**Comment by westnordost** [comment]
I noticed that I call
```
LocationServices.FusedLocationApi.removeLocationUpdates(lostApiClient, this);
lostApiClient.disconnect();
```
on multiple different occasions which means that this might be executed when the lost api client already disconnected. [I added a `lostApiClient.isConnected()` check](https://github.com/westnordost/StreetComplete/commit/97381ade7d02fe15987951fe98ce2d9f13e1cf3a), however this does not fix it, the exception is the same.

**Comment by westnordost** [comment]
I can not reproduce this with LOST 2.1.2, only with 2.2.0.

**Comment by westnordost** [comment]
Here is more info. After screen rotation finishes and the different fragments build and connect their LostApiClients, LostClientManager correctly adds the clients to its `clients `HashSet, but then, **after all this** but obviously **before the isConnected()**  this happens:

```
	  at com.mapzen.android.lost.internal.LostClientManager.shutdown(LostClientManager.java:231)
	  at com.mapzen.android.lost.internal.FusedLocationProviderServiceImpl.shutdown(FusedLocationProviderServiceImpl.java:45)
	  at com.mapzen.android.lost.internal.FusedLocationProviderService.onDestroy(FusedLocationProviderService.java:55)
	  at android.app.ActivityThread.handleStopService(ActivityThread.java:2988)
	  at android.app.ActivityThread.access$2200(ActivityThread.java:156)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
	  at android.os.Handler.dispatchMessage(Handler.java:102)
	  at android.os.Looper.loop(Looper.java:211)
	  at android.app.ActivityThread.main(ActivityThread.java:5389)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at java.lang.reflect.Method.invoke(Method.java:372)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by ecgreb** [comment]
I am able to reproduce a crash when rotating the `MultipleLocationListenerMultipleClientsActivity` in the Lost demo app but the stack trace is not the same.

```
04-04 16:27:11.846 6675-6675/com.example.lost E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.lost, PID: 6675
    java.lang.IllegalStateException: LostApiClient is not connected.
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.throwIfNotConnected(FusedLocationProviderApiImpl.java:189)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.requestLocationUpdates(FusedLocationProviderApiImpl.java:111)
    at com.example.lost.MultipleLocationListenerMultipleClientsActivity.initLocationTracking(MultipleLocationListenerMultipleClientsActivity.java:94)
    at com.example.lost.MultipleLocationListenerMultipleClientsActivity.access$000(MultipleLocationListenerMultipleClientsActivity.java:24)
    at com.example.lost.MultipleLocationListenerMultipleClientsActivity$1.onConnected(MultipleLocationListenerMultipleClientsActivity.java:57)
    at com.mapzen.android.lost.internal.FusedLocationServiceConnectionManager.onServiceConnected(FusedLocationServiceConnectionManager.java:86)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.onServiceConnected(FusedLocationProviderApiImpl.java:65)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
