### ISSUE TITLE
Could not run de lost-sample project

### ISSUE THREAD

**Issue by elcioabrahao** [mapzen/LOST#18]
Hi !
I m imported the lost-sample project to Android Studio and deploy the application to my device GT-N7100.

When the app starts it just give me the follow error message: SettingsActivity}: android.view.InflateException: Binary XML file line #5: Error inflating class com.mapzen.prefsplus.EditIntPreference (bellow is the full error).

I already tried to use the lib with grandle, and after this download the jar to the libs folder... nothing works...

I would really appreciate if you guys help me on this. I liked the lib and it would be nice to use it on one of my projects.

Thanks,

Elcio A.

    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.qpainformatica.mylostsample/br.com.qpainformatica.mylostsample.SettingsActivity}: android.view.InflateException: Binary XML file line #5: Error inflating class com.mapzen.prefsplus.EditIntPreference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2308)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
            at android.app.ActivityThread.access$700(ActivityThread.java:168)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5493)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class com.mapzen.prefsplus.EditIntPreference
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:326)
            at br.com.qpainformatica.mylostsample.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:40)
            at android.app.Fragment.performCreate(Fragment.java:1677)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:872)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1075)
            at android.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1455)
            at android.app.Activity.performStart(Activity.java:5381)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
            at android.app.ActivityThread.access$700(ActivityThread.java:168)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5493)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.prefsplus.EditIntPreference" on path: /data/app/br.com.qpainformatica.mylostsample-2.apk
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
            at android.preference.GenericInflater.createItem(GenericInflater.java:375)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:326)
            at br.com.qpainformatica.mylostsample.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:40)
            at android.app.Fragment.performCreate(Fragment.java:1677)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:872)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1075)
            at android.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1455)
            at android.app.Activity.performStart(Activity.java:5381)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2362)
            at android.app.ActivityThread.access$700(ActivityThread.java:168)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5493)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)

**Comment by ecgreb** [comment]
Hi. The sample project doesn't support Gradle builds. Please try building with Maven (version 3.1.1 or higher).

As for including the LOST library in a Gradle project this should work fine. I recommend including as an external module dependency rather than a local file dependency.

```groovy
compile 'com.mapzen.android:lost:1.0.0'
```

**Comment by elcioabrahao** [comment]
Thanks !!!!

2015-02-17 19:38 GMT-02:00 Chuck Greb <notifications@github.com>:

> Hi. The sample project doesn't support Gradle builds. Please try building
> with Maven (version 3.1.1 or higher).
>
> As for including the LOST library in a Gradle project this should work
> fine. I recommend including as an external module dependency rather than a
> local file dependency.
>
> compile 'com.mapzen.android:lost:1.0.0'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapzen/LOST/issues/18#issuecomment-74759473>.
>



-- 


################################################
Jedi Order:

There is no emotion, there is peace.

There is no ignorance, there is knowledge.

There is no passion, there is serenity.

There is no chaos, there is harmony.

There is no death, there is Force.

Our Jedi Code: May peace and force be with you.

Our Vulcan Salute: Live longer and prosper.
