### ISSUE TITLE
IllegalStateException on onLocationChanged

### ISSUE THREAD

**Issue by westnordost** [mapzen/lost#224]
The following exception is reported by many of my users:
```
java.lang.IllegalStateException: 
  at com.mapzen.android.lost.internal.FusedLocationServiceCallbackManager.onLocationChanged(FusedLocationServiceCallbackManager.java:31)
  at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1$1.run(FusedLocationProviderApiImpl.java:46)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

### Lost & Android Version
3.0.0
on Android 6.0, Android 7.0, Android 7.1
not on any version below Android 6.0 yet (but there are only 28 reports in total)

Unfortunately, I can not give any more details about it as I was not able to reproduce it myself yet. 

A helpful comment here: https://github.com/mapzen/lost/issues/218#issuecomment-310485055

**Comment by westnordost** [comment]
I got this on an Android 5.1.1 device right now and I can reproduce it reliably in StreetComplete with LOST 3.0.1. Simply tab out while the location is displayed.

```
java.lang.IllegalStateException: Location update received after client was disconnected. Did you forget to unregister location updates before disconnecting?
    at com.mapzen.android.lost.internal.FusedLocationServiceCallbackManager.onLocationChanged(FusedLocationServiceCallbackManager.java:31)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl$1$1.run(FusedLocationProviderApiImpl.java:48)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:211)
    at android.app.ActivityThread.main(ActivityThread.java:5389)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

via onStop, the code looks like this:
```
if(lostApiClient.isConnected())
{
	LocationServices.FusedLocationApi.removeLocationUpdates(lostApiClient, SingleLocationRequest.this);
	lostApiClient.disconnect();
}
```

(Note: In StreetComplete, there are 3 different objects that receive location updates. But all of these unregister using the code above.)

**Comment by Binnette** [comment]
I can reproduce the crash. See my issue for details : westnordost/StreetComplete#354
Also I can debug it, if you provide me some instructions or breakpoints because I try to debug it on my own without sucess.

**Comment by westnordost** [comment]
Perhaps set a breakpoint at where service is set to null to find out why it is already null there.

This crash looks very similar to #178, not sure if it is exactly the same.
